### PR TITLE
German <r> and long vowel handling

### PR DESCRIPTION
**Pull request by ebrahimebrahim**
After using Epitran on some german text, I noticed it was not handling \<r\> properly.
I added some rewrite rules to address this, mainly using information from [here](https://www.omniglot.com/writing/german.htm).
In the process, I also noticed that there were issues with long vowels-- the vowel lengthening rule is allowed to lengthen already long vowels in certain cases.

Here is is list of German words, some from the examples in the link given above:
```['Kurs', 'futur', 'Markt', 'Haar', 'trinken', 'hören', 'intentional', 'Wasser', 'Wehr', 'Ähre']```
Before my changes their transliterations were
``` ['kurs', 'fuːtur', 'markt', 'haːr', 'triŋkən', 'høoːrən', 'intəntioːnal', 'vasər', 'veːr', 'eːrə'] ```
And after the changes they are
```['kuəs', 'fuːtuə', 'makt', 'haː', 'tʁiŋkən', 'høʀən', 'intəntsioːnal', 'vasə', 'veːə', 'eːʀə']```

A couple of points to note:
- I'm not a German speaker or a linguist, so my suggested changes could really use a second look.
- I chose to use [ə] in several places where [ɐ] is technically more accurate-- this was only to stay consistent with some choices that were already present.

### CODE REVIEW

**Comment by dmort27** [comment]
Thanks for the PR. The changes re: vowel lengthening are good. With regards to <r>, the rules you added yield a fine-grained *phonetic* representation. The policy, with Epitran, is to produce *phonemic* representations (so the deletion rule after <a> would still stand but the different realizations of <r> as [ʀ], [ʁ], etc. would not stand. Note, too, that these realizations of /r/ are only present in some varieties of German. Perhaps we can create a separate "mode" for narrow phonetic German (`deu-Latn-nar`) that includes your rules. In that case, you should use [ɐ] rather than [ə] in the <r> realization rule since these are different phonetically.

**Comment by ebrahimebrahim** [comment]
I see, that makes sense. When choosing an IPA symbol to represent the phoneme, shouldn't the symbol be at least one of the allophones? Since [r] does not show up in German (right? I think) would it be better to call the phoneme something like /ʁ/ instead of /r/? In that case I would make the change in grapheme-to-phoneme mapping, simply substituting ʁ for r.

There's no need to accommodate my fine-grained phonetic rules with a special mode, unless you actually want that to be available. For me I'd rather keep to the stated design goals of the project. Thanks for reviewing my contribution!

I will update this PR shortly.

**Comment by dmort27** [comment]
/r/ does not show up in Standard German, but in more conservative varieties of German, it is the main realization of <r>. Since one of the use-cases of Epitran is mapping related words (cognates, loanwords) from different languages into maximally similar representations, it is useful to use conservative forms, rather than prescriptively standard forms. However, for people who are interested in using Epitran for G2P, having something more phonetically realistic is desirable, so it probably makes sense to have two modes.

**Comment by ebrahimebrahim** [comment]
Alright PR updated!

Starting with the list of words
```
['Kurs', 'futur', 'Markt', 'Haar', 'trinken', 'hören', 'intentional', 'Wasser', 'Wehr', 'Ähre']
```
transliterating them using `deu-Latn` yields
```
['kuəs', 'fuːtuə', 'makt', 'haː', 'triŋkən', 'høːrən', 'intəntsioːnal', 'vasə', 'veːə', 'eːrə']
```
and transliterating them using `deu-Latn-nar` yields
```
['kuɐs', 'fuːtuɐ', 'makt', 'haː', 'tʁiŋkən', 'høːʀən', 'intəntsioːnal', 'vasɐ', 'veːɐ', 'eːʀə'].
```

Let me know what you think.

A couple of other questions:
- I see that you've got some unit tests sitting in the repo. How do you actually run those tests? I'd like to add some for `deu-Latn-nar`.
- Where should `deu-Latn-nar` be documented?

**Comment by dmort27** [comment]
Thanks, this looks good. How you run the unit tests depends on which version of python and unittest you are using. For python 3, you just execute `python -m unittest` in the directory where the tests reside.

`deu-Latn-nar` should be documented in the README.md, in the table with the other modes.

**Pull request merged**
